spring.application.name=apos

#JWT
# Custom JWT secret property
jwt.secret=bWlfY2xhdmVfc2VjcmV0YV9qd3RfbXV5X2xhcmdhX3BhcmFfMjRiZXRfYXBwbGljYXRpb25fMjAyNA==
# Tiempo de expiración en milisegundos (1 día)
jwt.expiration=86400000 


# Configuración de la base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Optimización de Hibernate y JPA para batch processing
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=25
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

spring.jpa.show-sql=false
