export enum CategoriaMovimiento {
    INSUMOS= "INSUMOS",
    NÓMINA= "NÓMINA",
    RENTA= "RENTA",
    SERVICIOS= "SERVICIOS",
    TRANSPORTE= "TRANSPORTE",
    MANTENIMIENTO= "MANTENIMIENTO",
    PUBLICIDAD= "PUBLICIDAD",
    EQUIPO= "EQUIPO",
    IMPUESTOS= "IMPUESTOS",
    OTROS= "OTROS"
}
